name: Test Script
on: 
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, edited]

jobs:
  rust-setup:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Execute Script
        run: |
          ./setup.sh
      - name: Verify Installation
        run: |
          rustup --version
          cargo --version
          cargo install-update --version