name: Test Script
on: push

jobs:
  name-of-job:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Execute Script
        run: |
          ./setup.sh
      - name: Verify Installation
        run: |
          rustup --version
          cargo --version
          cargo install-update --version