name: Test Script
on: 
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, edited]

jobs:
  rust-setup:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Execute & Verify Script
        run: |
          $GITHUB_WORKSPACE/setup.sh
          $GITHUB_WORKSPACE/verify.sh